version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: jimseconde
       MYSQL_DATABASE: jimseconde_wcplugin
       MYSQL_USER: jimseconde
       MYSQL_PASSWORD: jimseconde

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: jimseconde
       WORDPRESS_DB_PASSWORD: jimseconde
       WORDPRESS_DB_NAME: jimseconde_wcplugin
volumes:
    db_data: {}
